name: Blog
on:
  schedule: [{cron: "0 */24 * * *"}]
  workflow_dispatch:
  # push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.blog.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://ahampriyanshu.com/blog/feed
          plugin_rss_limit: 8